name: 'publish'

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: 'ubuntu-latest'

    permissions:
      contents: 'write'
      pull-requests: 'read'

    steps:
      - uses: 'actions/checkout@v3'

      - name: 'Publish Release'
        uses: 'azurystudio/log@v1'
